spring:
  application:
    name: E-Commerce

  datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce_database
    username: root
    password: dayanand


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

#  security:
#    user:
#      name: admin
#      password: admin123



